apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd    # same namespace which ArgoCD installed
spec:
  project: default   # every application belongs to a single project.

  source:
    repoURL: https://github.com/muratyarali/githubactions-task.git
    targetRevision: HEAD    # Follow always the last commit in repo
    path: part3-deployment
  
  destination:
    server: https://kubernetes.default.svc    # Because ArgoCD is deployed in same K8S Cluster, it has to be endpoint of K8s API Server
    namespace: myapp    # There is not a namespace named as myapp but it will be created automatically
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:    # automatically track and sync
      selfHeal: true     # undo/override any manual changes into manifest yaml files
      prune: true    # delete components after some deletion process