name: Hello World workflow

on:
  # push:
  #   branches:
  #     - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello_world
        run: echo "Hello World 2"
        shell: bash
  
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbye_world
        run: echo "Goodbye world"
        shell: bash
