name: Matrix

on: pull_request

jobs:
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [14, 15, 16]
        include:
          - os: ubuntu-latest
            node_version: 16
            is_ubuntu_16: "true"
        exclude:
          - os: ubuntu-latest
            node_version: 15
          - os: macos-latest
            node_version: 16
      # max-parallel: 2
      # fail-fast: true

    runs-on: ${{ matrix.os}}
    env:
      IS_UBUNTU_16: ${{ matrix.is_ubuntu_16 }} # This variable only we are running "ubuntu-latest" and "16"

    steps:
      - name: Log node version
        run: node -v
      
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_16