FROM python:alpine
RUN pip install flask
WORKDIR /app
COPY part1-src/hello-world/hello.py /app
EXPOSE 80
CMD python3 ./hello.py

C:\Users\murat\OneDrive\Desktop\murat-naxtech\my-workspace\githubactions-task\part1-src\hello-world\hello.py