name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: muratyarali/githubactions

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and pushh
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:v1.0.5, ${{ env.IMG_NAME }}:latest

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            image: ${{ env.IMG_NAME }}:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
                python ./hello.py