name: ci

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build-hello-app:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: muratyarali/githubactions-hello-app

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./part1-src/hello-world/Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:v1.0.0, ${{ env.IMG_NAME }}:latest

      - name: Install Docker      
        uses: docker-practice/actions-setup-docker@master
      # - run: |
      #     docker version

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            image: docker.io/${{ env.IMG_NAME }}:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
                docker version
                docker ps -a
                docker images
                #docker run -d --name hello-app ${{ env.IMG_NAME }}:latest


  build-welcome-app:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: muratyarali/githubactions-welcome-app

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./part1-src/welcome-nax/Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:v1.0.0, ${{ env.IMG_NAME }}:latest

      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            image: docker.io/${{ env.IMG_NAME }}:latest
            options: -v ${{ github.workspace }}:/var/www
            run: |
                # docker ps -a
                #ocker --version
                # docker run -d --name welcome-app ${{ env.IMG_NAME }}:latest