name: Create Images and Deploy

on:
  # push:
  #   paths:
  #     - 'part1-src/**'
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  IMG_VERSION: v1.0.0
  CLUSTER_NAME: devopsthehardway-cluster   # It has to be same with aws_eks_cluster name in /part2-infra-detailed/main.tf

jobs:
  build-hello-app:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: muratyarali/githubactions-hello-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./part1-src/hello-world/Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:${{ env.IMG_VERSION }}, ${{ env.IMG_NAME }}:latest

  build-welcome-app:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: muratyarali/githubactions-welcome-app

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./part1-src/welcome-nax/Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:${{ env.IMG_VERSION }}, ${{ env.IMG_NAME }}:latest
 
  deploy-eks-cluster:
    runs-on: ubuntu-latest
    needs: [build-hello-app, build-welcome-app]
    steps:

      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.2' # default is latest stable (find latest stable version on storage.googleapis.com/kubernetes-releases/release/stable.txt)
        id: install

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Deploy Image to Amazon EKS
        run: |
          kubectl apply -f part3-deployment/aws-auth.yaml
          kubectl apply -f part3-deployment/hello-app.yaml
          kubectl apply -f part3-deployment/hello-app.yaml
          kubectl apply -f part3-deployment/ingress-service.yaml