name: Create Images

on:
  # push:
  #   paths:
  #     - 'part1-src/**'
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:

env:
  IMG_VERSION: v1.0.1
  CLUSTER_NAME: devopsthehardway-cluster   # It has to be same with aws_eks_cluster name in /part2-infra-detailed/main.tf

jobs:
  build-hello-app:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: muratyarali/githubactions-hello-app

    steps:
      - name: Checkout
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./part1-src/hello-world/Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:${{ env.IMG_VERSION }}, ${{ env.IMG_NAME }}:latest

  build-welcome-app:
    runs-on: ubuntu-latest
    env:
      IMG_NAME: muratyarali/githubactions-welcome-app

    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./part1-src/welcome-nax/Dockerfile
          push: true
          tags: ${{ env.IMG_NAME }}:${{ env.IMG_VERSION }}, ${{ env.IMG_NAME }}:latest