name: ci

on:
  push:
    paths:
      - 'part2-infra-detailed/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        working-directory: part2-infra-detailed/
        run: |
          terraform init

      - name: Terraform Format
        working-directory: part2-infra-detailed/
        run: terraform fmt

      - name: Terraform Validate
        working-directory: part2-infra-detailed/
        run: terraform validate

      - name: Terraform Plan
        working-directory: part2-infra-detailed/
        run: terraform plan

      - name: Terraform Apply
        working-directory: part2-infra-detailed/
        run: terraform apply -auto-approve