name: Create-Infra

on:
  push:
    paths:
      - 'part2-infra-detailed/**'
  workflow_dispatch:

env:
  BUCKET_NAME: terraform-up-and-running-state-nax   # It has to be same with bucket name in /part2-infra-detailed/backent-tf/main.tf

defaults:
  run:
    working-directory: ./part2-infra-detailed/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve
          sleep 300